license = "${license}"
issueTrackerURL = "${issue_tracker}"

[[mods]]
    modId = "${mod_id}"
    version = "${version}"
    displayName = "${mod_name}"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/female-gender"
    iconFile = "assets/${mod_id}/icon.png"
    bannerFile = "assets/${mod_id}/banner.png"
    authors = "${authors}"
    credits = "${contributors}"
    description = "${description}"

[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}.neo.mixins.json"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    side = "BOTH"
[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge_version},)"
    side = "BOTH"
